version: '2'
services:
  elasticsearch-masters:
    image: rancher/elasticsearch-conf:v0.5.0
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: elasticsearch-base-master,elasticsearch-datavolume-masters
    volumes_from:
      - elasticsearch-datavolume-masters
  elasticsearch-datavolume-masters:
    labels:
      elasticsearch.datanode.config.version: '0'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esconfig:/usr/share/elasticsearch/config
      - esconfigbin:/opt/rancher/bin
    entrypoint: /bin/true
    image: elasticsearch:2.4.1
  elasticsearch-base-master:
    labels:
      elasticsearch.master.config.version: '0'
      io.rancher.container.hostname_override: container_name
    image: elasticsearch:2.4.1    
    volumes_from:
      - elasticsearch-datavolume-masters
    network_mode: container:elasticsearch-masters
    entrypoint:
      - /opt/rancher/bin/run.sh

  nuxeo-datavolume:
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
    image: ${nuxeoimage}
    entrypoint: /bin/true
    volumes:
      - nxdata:/var/lib/nuxeo/data
      - nxlog:/var/log/nuxeo

  nuxeo:
    environment:
      NUXEO_CLID: ${clid}
      NUXEO_PACKAGES: ${packages}
      NUXEO_DATA: /var/lib/nuxeo/data/
      NUXEO_LOG: /var/log/nuxeo/    
      NUXEO_URL: https://${traefikalias}.${traefikdomain}/
      NUXEO_ES_HOSTS: elasticsearch:9300
      NUXEO_ES_CLUSTERNAME: elasticsearch
      NUXEO_ES_INDEX_NAME: nuxeo
      NUXEO_ES_REPLICAS: 0
      NUXEO_CUSTOM_PARAM: |
        mail.transport.host=smtp
        mail.from=${mailfrom}
        ${customconf}
    labels:
      io.rancher.sidekicks: nuxeo-datavolume    
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      traefik.enable: true
      traefik.alias: ${traefikalias}
      traefik.domain: ${traefikdomain}
      traefik.acme: ${traefikacme}
      traefik.port: 8080
    image: ${nuxeoimage}
    volumes_from:
    - nuxeo-datavolume
    links:
    - elasticsearch-masters:elasticsearch
    external_links:
    - ${smtprelay}:smtp

volumes:
  esdata:
    driver: ${volumedriver}
  esconfig:
    driver: local
  esconfigbin:
    driver: local
  nxdata:
    driver: ${volumedriver}
  nxlog:
    driver: local
    per_container: true
