nuxeo-datavolume:
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.container.hostname_override: container_name
  image: ${nuxeoimage}
  entrypoint: /bin/true
  volume_driver: ${volumedriver}
  volumes:
    - /var/lib/nuxeo/data
    - /var/log/nuxeo

nuxeo:
  environment:
    NUXEO_CLID: ${clid}
    NUXEO_PACKAGES: ${packages}
    NUXEO_DATA: /var/lib/nuxeo/data/
    NUXEO_LOG: /var/nuxeo/log/    
    NUXEO_URL: https://${traefikalias}.${traefikdomain}/
  labels:
    io.rancher.sidekicks: nuxeo-datavolume    
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    traefik.enable: true
    traefik.alias: ${traefikalias}
    traefik.domain: ${traefikdomain}
    traefik.acme: true
    traefik.port: 8080
  image: ${nuxeoimage}
  volumes_from:
  - nuxeo-datavolume
