.catalog:
  name: "Nuxeo Platform"
  version: "1.0"
  description: |
    Enterprise Content Management 
    Platform for Business Applications
  questions:
    - variable: traefikalias
      description: "Subdomain to use (url will be https://{subdomain}.{domain}/"
      label: "Subdomain"
      type: "string"
      required: true
    - variable: traefikdomain
      description: "Domain to use (url will be https://{subdomain}.{domain}/"
      label: "Domain"
      type: "string"
      required: true
      default: "prod.io.nuxeo.com"
    - variable: clid
      description: "A valid CLID to be able to download packages from Nuxeo Online Services. in the form part1\npart2"
      label: "CLID"
      type: "string"
      required: false
      default: ""
    - variable: "nuxeoimage"
      type: "string"
      label: "Nuxeo image"
      description: |
        Nuxeo docker image to use (Rancher must have access to repository)
      default: "nuxeo:LTS"
    - variable: "packages"
      type: "string"
      label: "List of Nuxeo packages"
      description: |
        List of Nuxeo packages 
      default: "nuxeo-web-ui"
    - variable: volumedriver
      type: "string"
      label: "Volume driver"
      description: |
        Specifiy docker volume driver to use
      default: local
    



nuxeo:
  scale: 2
  health_check:
    port: 8080
    # Interval is measured in milliseconds
    interval: 5000
    unhealthy_threshold: 5
    # For TCP, request_line needs to be ''
    # TCP Example: 
    # request_line: ''
    request_line: GET /nuxeo/login.jsp 
    healthy_threshold: 2
    # Response timeout is measured in milliseconds
    response_timeout: 2000

elasticsearch-masters:
  scale: 3
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "true"
        node.master: "true"
        network.host: "_site_"

