.catalog:
  name: "Arken"
  version: "0.1"
  description: |
    High level app management on top of rancher
  minimum_rancher_version: "v1.0.0"
  questions:
    - variable: "GOGETAPORT"
      description: "Public port on which Gogeta will listen"
      label: "Gogeta port:"
      required: true
      default: "7777"
      type: "string"
    - variable: "REPLICAS"
      description: "Number of Etcd nodes. 3, 5, or 7 are good choices"
      label: "Etcd cluster size:"
      required: true
      default: 3
      type: "int"
etcd:
  retain_ip: true
  scale_policy:
    min: 1
    max: ${REPLICAS}
    increment: 1
  health_check:
    port: 2378
    request_line: /health
    interval: 5000
    response_timeout: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
